### ISSUE TITLE
some details about this code

### ISSUE THREAD

**Issue by Yanxing-Shi** [ndehio/2019_ICRA#1]
Hi,this is very interesting work.Thank you for sharing you source code.Could you please provide some details about this code.Thank you!

**Comment by ndehio** [comment]
What exactly are you interested in? Feel free to check out my recent work which explains the DynGHC approach in detail: 
https://www.researchgate.net/profile/Niels_Dehio/publication/331320218_Dynamically-consistent_Generalized_Hierarchical_Control/links/5c73b23892851c69503e6674/Dynamically-consistent-Generalized-Hierarchical-Control.pdf
